config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :lists, only: [ :index, :show, :new, :create, :destroy ] do
    resources :bookmarks, only: [:new, :create]
    resources :reviews, only: [:create]
  end

  resources :bookmarks, only: [:destroy]

  root to: 'lists#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :list
  belongs_to :movie

  validates :comment, length: { minimum: 6 }
  validates_uniqueness_of :list_id, scope: :movie_id
end

app/models/list.rb
class List < ApplicationRecord
  has_many :bookmarks, dependent: :destroy
  has_many :movies, through: :bookmarks
  has_many :reviews, dependent: :destroy
  has_one_attached :photo

  validates :name, presence: true, uniqueness: true
  validates :photo, presence: true
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks

  validates :title, uniqueness: true, presence: true
  validates :overview, uniqueness: true, presence: true
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :list

  validates :content, presence: true
  validates :rating, presence: true, inclusion: { in: 0..5 }, numericality: { only_integer: true }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  def new
    @list = List.find(params[:list_id])
    @bookmark = Bookmark.new
  end

  def create
    @list = List.find(params[:list_id])
    @bookmark = Bookmark.new(bookmark_params)
    @bookmark.list = @list

    if @bookmark.save
      redirect_to list_path(@list)
    else
      render :new
    end
  end

  def destroy
    @bookmark = Bookmark.find(params[:id])
    @bookmark.destroy

    redirect_to list_path(@bookmark.list)
  end

  private

  def bookmark_params
    params.require(:bookmark).permit(:comment, :list_id, :movie_id)
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  def index
    @lists = List.all
  end

  def show
    @list = List.find(params[:id])
    @bookmark = Bookmark.new
    @review = Review.new
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)

    if @list.save
      redirect_to list_path(@list)
    else
      render :new
    end
  end

  def destroy
    @list = List.find(params[:id])
    @list.destroy

    redirect_to lists_path
  end

  private

  def list_params
    params.require(:list).permit(:name, :photo)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def create
    @list = List.find(params[:list_id])
    @review = Review.new(review_params)
    @review.list = @list
    @review.save

    redirect_to list_path(@list)
  end

  private

  def review_params
    params.require(:review).permit(:content, :rating)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/application/_banner.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url('<%= image_url 'canva_banner_yellow(1).png' %>');">
  <div class="container">
  </div>
</div>

app/views/application/_navbar.html.erb
<div class="navbar sticky-top navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <a class="navbar-brand" href="<%= lists_path %>" style="font-size: 25px;">
      <%= image_tag "logo.svg" %>
</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
          <li class="nav-item active">
            <%= link_to "Home", lists_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
          <%= link_to "Create list", new_list_path, class: "nav-link" %>
          </li>
      </ul>
    </div>
  </div>
</div>

app/views/bookmarks/new.html.erb
<div class="container">
<%= simple_form_for [ @list, @bookmark ]  do |f| %>
  <%= f.input :comment %>
  <%= f.association :movie %>
  <%= f.button :submit, class: "btn btn-primary" %>
<% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <%= render "navbar" %>
    <%= yield %>
  </body>
</html>

app/views/lists/index.html.erb
<%= render 'banner' %>

<div class="container m-3 p-3">
  <h2>My movie lists <%= link_to "Create a movie list", new_list_path, class: "btn btn-dark"  %> </h2>

    <div class="cards">
      <% @lists.each do |list| %>
        <a class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('<%= cl_image_path list.photo.key, crop: :fit %>');" href="<%= list_path(list) %>">
          <%= list.name %>
        </a>
      <% end  %>
    </div>
</div>

app/views/lists/new.html.erb
<div class="container mt-3">
<h2>Create a new list</h2>
<%= simple_form_for [ @list ] do |f| %>
  <%= f.input :name %>
  <%= f.input :photo, as: :file %>
  <%= f.submit "Create list", class: "btn btn-primary" %>
<% end %>
</div>

app/views/lists/show.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url('<%= cl_image_path @list.photo.key, crop: :fit %>');">
  <div class="banner-container">
    <h1 style="text-align: center;"><%= @list.name %></h1>
  <div class="delete-button"><%= link_to "Delete list", list_path(@list), class: "btn btn-light", method: :delete, data: { confirm: "Are you sure you want to delete this list?"} %></div>
  </div>
</div>



<div class="container m-4 p-3">

  <h2 class="m-3">Bookmarks   <%= link_to "Add movie", new_list_bookmark_path(@list), class: "btn btn-dark"  %></h2>

    <div class="cards m-3">
      <% @list.movies.each do |movie| %>
      <% bookmark = Bookmark.find_by(list: @list, movie: movie) %>
          <div class="card-trip">
            <img src="<%= movie.poster_url %>" />
              <div class="card-trip-infos">
                <div class="flexible">
                  <h2><%= movie.title %> • <%= movie.rating %> <i class="fas fa-star"></i></h2>
                  <p><%= movie.overview %></p>
                </div>
              </div>
                <div class="card-trip-pricing"
                ><p><i class="fas fa-quote-left"></i> <%= bookmark.comment %></p>
                <h2><%= link_to "Delete", bookmark_path(bookmark), method: :delete, data: { confirm: "Are you sure you want to delete this bookmark?"} %></h2>
                </div>
          </div>
      <% end  %>
    </div>
</div>


<div class="container border-top border-3 mb-5">
<div class="row mt-4">

<div class="col-6 p-3">
<h2>Reviews</h2>
<ul class="list-group list-group-flush">
<% @list.reviews.each do |r| %>

  <li class="list-group-item bg-transparent"><%= r.content %> <%= r.rating %> / 5 <%= image_tag "269.png" %></li>

<% end %>
</ul>
</div>

<div class="review-form-container col-6 p-3">
<div><%= simple_form_for [ @list, @review ] do |f| %>
  <%= f.input :content, label: "Leave your review here"  %>
  <%= f.input :rating, collection: 0..5 %>
  <%= f.submit "Submit review", class: "btn btn-primary btn-sm" %>
<% end %></div>
</div>
</div>
</div>